version: '3.8'

services:
    tarantool1:
        image: tarantool/tarantool
        container_name: tarantool1
        networks:
            - dev-back
        ports:
            - "3301:3301"
        volumes:
            - ./data/tarantool1:/var/lib/tarantool
        environment:
            TARANTOOL_REPLICATION: "tarantool1,tarantool2"
            TARANTOOL_USER_NAME: admin
            TARANTOOL_USER_PASSWORD: 123456
            TARANTOOL_SLAB_ALLOC_ARENA: 0.1
    
    tarantool2:
        image: tarantool/tarantool
        container_name: tarantool2
        networks:
            - dev-back
        ports:
            - "3302:3301"
        volumes:
            - ./data/tarantool2:/var/lib/tarantool
        environment:
            TARANTOOL_REPLICATION: "tarantool1,tarantool2"
            TARANTOOL_USER_NAME: admin
            TARANTOOL_USER_PASSWORD: 123456
            TARANTOOL_SLAB_ALLOC_ARENA: 0.1
    admin:
        image: quay.io/basis-company/tarantool-admin
        container_name: tarantool-admin
        ports:
            - "8888:80"
        networks:
            - dev-back
        depends_on:
            - tarantool1
            - tarantool2

networks:
    dev-back:
        driver: bridge
        name: dockernet-local
